"""Smoke tests auto-generated by uv-audit. Verify basic importability."""
import importlib
import pytest

# Package install name → Python import name.
# Most follow: lowercase, hyphens→underscores. Known exceptions listed below.
_KNOWN_IMPORT_NAMES = {
    "pillow": "PIL",
    "scikit-learn": "sklearn",
    "beautifulsoup4": "bs4",
    "python-dateutil": "dateutil",
    "opencv-python": "cv2",
    "pyyaml": "yaml",
    "typing-extensions": "typing_extensions",
    "python-dotenv": "dotenv",
    "psycopg2-binary": "psycopg2",
    "mysqlclient": "MySQLdb",
}

# Replace this list with the actual import names derived from pyproject.toml.
# Apply _KNOWN_IMPORT_NAMES mappings; fall back to pkg.lower().replace("-", "_").
# Omit CLI-only tools with no importable API: black, ruff, mypy, pytest, etc.
PACKAGES: list[str] = []


@pytest.mark.parametrize("import_name", PACKAGES)
def test_can_import(import_name: str) -> None:
    importlib.import_module(import_name)
